workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "push"

stages:
  - build
  - generate_reports
  - deploy_reports
  - deploy_docs

pre-commit:
  stage: build
  image: registry.cern.ch/docker.io/library/python:3.12
  script:
    - pip install pre-commit
    - pre-commit run --all-files
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never

# get_secret:
#   stage: generate_reports
#   image:
#     name: "gitlab/glab"
#     entrypoint: [""]
#   script:
#     - glab --version
#     - glab auth login --hostname $CI_SERVER_FQDN --job-token $CI_JOB_TOKEN
#     - glab securefile download --all
#   artifacts:
#     paths:
#       - ./config_api
#     expire_in: 10 min
#     access: 'maintainer'
#   rules:
#     - if: $CI_PIPELINE_SOURCE == "schedule"
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#     - if: $CI_PIPELINE_SOURCE == "merge_request_event"

generate_files:
  stage: generate_reports
  #needs: ["get_secret"]
  image: registry.cern.ch/docker.io/library/python:3.12
  script:
    - echo "🔧  Installing dependencies"
    - pip install -r requirements.txt
    - echo "$CONFIG_API" > config_api
    - echo "" > config_api
    - chmod 600 config_api
    - echo "🛠️  Running your yields report"
    - python report_stats.py --log-axis True
    - shred -u config_api
    - mkdir generated
    - cp counts*.pdf generated
    - cp counts*.png generated
    - cp fractions*.pdf generated
    - cp fractions*.png generated
    - cp newly_uploaded*.pdf generated
    - cp newly_uploaded*.png generated
    - cp cumulative_counts*.pdf generated
    - cp cumulative_counts*.png generated
    - cp report_stats*.json generated
    - cp output_invalid.txt generated
  artifacts:
    paths:
      - generated/
    expire_in: 1h
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

sync_to_eos:
  stage: deploy_reports
  needs: [generate_files]
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer
  variables:
    "EOS_PATH": "${EOS_HGTD_PATH}"
    "EOS_ACCOUNT_USERNAME": "${EOS_ACCOUNT_USERNAME}"
    "EOS_ACCOUNT_PASSWORD": "${EOS_ACCOUNT_PASSWORD}"
    "CI_OUTPUT_DIR": "generated/"
  script:
    - echo "📂 ${EOS_ACCOUNT_USERNAME} will copy generated files into hgtd eos space"
    - deploy-eos
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never


.job-script: &job-script
  - pip install zensical
  - zensical build --clean

pages:
  stage: deploy_docs
  image: registry.cern.ch/docker.io/library/python:latest
  script: [*job-script, "if [[ -f _redirects ]]; then cp _redirects public; fi;"]
  artifacts:
    paths:
      - public
    expire_in: 1 hour
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
