stages:
  - report

report-stats:
  stage: report
  image: registry.cern.ch/docker.io/library/python:3.12
  needs: [ ]
  before_script:
    - pip install -r requirements.txt
    - |
      git config --global user.email "hgtd-tools-bot@cern.ch"
      git config --global user.name "hgtd-tools-bot"
      # Need expanded token here to push
      #git remote set-url origin https://hgtdci:$CI_ACCESS_TOKEN@gitlab.cern.ch/$CI_PROJECT_PATH.git
      #git config --list
  variables:
    SECURE_FILES_DOWNLOAD_PATH: './'
  script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - echo "Testing runner"
    #- touch config_api
    #- cat config_api
    #- echo $TESTVAR >> config_api
    #- cat config_api
    #- echo $hgtdapi_secret >> config_api
    - python report_stats.py
