repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: requirements-txt-fixer
-   repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.28.0
    hooks:
    -   id: pyproject-fmt
        args: ["--table-format=long"]
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format
